feat: login and register done
atlp-rwanda/rca-barefoot-team6-fe pull request #4
Opened 2023-04-10 12:35 UTC by felixdusengimana

#### What does this PR do?
 
Implementing login and register on frontend.

#### Description of  the task to be completed?

I have done implementation of login and register on frontend part with user

#### How should this be manually tested?

Check out this repo and then run `npm i` after successful installation run `npm run dev` then go into browser at this URL `{BASE_URL}/auth/login` or `{BASE}/auth/register` for register.

#### Any background context you want to provide?

I have used `react-query` so someone implementing other request via frontend should understand it.

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

<img width="955" alt="image" src="https://user-images.githubusercontent.com/73703812/230902465-f32eb56a-dcc8-4433-b85a-49d04fc1239e.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/73703812/230902493-9da77ab6-8abb-440f-9b1f-611bcf2e5b87.png">

2023-04-17 09:38 UTC, Nkbtemmy requested changes
Remember to check UI/UX before pushing !!

2023-04-17 09:38 UTC, Nkbtemmy commented on src/plugins/axios.ts
> +};
Please use .env file for accessing BASE_URL as well as other credentials

2023-04-17 09:41 UTC, felixdusengimana commented
> Remember to check UI/UX before pushing !!

> Let me solve that

2023-04-26 12:46 UTC, Nkbtemmy approved these changes

2023-04-26 12:50 UTC, Nkbtemmy requested changes
You need to rebase updated develop

2023-04-26 12:51 UTC, Nkbtemmy commented
Or do npm install before you push

2023-04-27 15:13 UTC, Nkbtemmy approved these changes

2023-04-27 15:15 UTC, merged